require("lua.core.variables")
require("lua.core.bind")
require("lua.core.monitors")
require("lua.core.workspaces")
require("lua.core.lid")
require("lua.core.environment")
require("lua.core.autostart")
require("lua.core.input")
require("lua.core.options")
require("lua.core.animations")
require("lua.core.zoom")
require("lua.core.minimal")
require("lua.core.presenting")

require("lua.keymaps.loader")

require("lua.rules.windows")
require("lua.rules.layers")
