-- Zastąpione przez aerial.nvim (lua/plugins/aerial.lua); zostawione na wypadek powrotu.
return {}

-- return {
-- 	"hedyhli/outline.nvim",
-- 	cmd = { "Outline", "OutlineOpen" },
-- 	opts = {
-- 		outline_window = {
-- 			position = "right",
-- 			width = 30,
-- 			auto_close = false,
-- 		},
-- 		outline_items = {
-- 			show_symbol_details = true,
-- 			show_symbol_lineno = false,
-- 		},
-- 		symbol_folding = {
-- 			autofold_depth = false,
-- 		},
-- 		preview_window = {
-- 			auto_preview = false,
-- 		},
-- 	},
-- 	keys = {
-- 		{ "<leader>o", "<cmd>Outline<cr>", desc = "Toggle symbol outline" },
-- 	},
-- }
